version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "Dependencies"
      - "Java"

  - package-ecosystem: "pnpm"
    directory: "/src/main/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "Dependencies"
      - "JavaScript"
    groups:
      angular-upgrade:
        patterns:
          - "@angular*"
          - "typescript"
